# Build spigot

name: Build Spigot

# Controls when the workflow will run
on:
  push:
  schedule:
    - cron: '0 23 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

#       # Runs a single command using the runners shell
#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'
          
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           python -m pip install requests
          
#       - uses: actions/setup-java@v3
#         with:
#           distribution: 'zulu'
#           java-version: |
#             8
#             11
#             16
#             17
        
#       - name: Run script
#         run: |
#           python run.py
#           /usr/bin/sh start.sh
          
      - name: Run script
        run: |
          sudo apt install wget
          wget "https://github.com/z0z0r4/bing-wallpaper-action/raw/main/wallpaper_cache/%E2%80%9C%E7%BE%A4%E5%B1%B1%E6%8B%A5%E6%9C%89%E6%8A%9A%E6%85%B0%E5%92%8C%E6%B2%BB%E6%84%88%E7%9A%84%E5%8A%9B%E9%87%8F%E2%80%9D_20230106_zh-CN_c04031.png" -O achieved/img.jar

      - uses: actions/upload-artifact@v3
        with:
          name: spigot-jar
          path: achieved/***.jar
